### ISSUE TITLE
No such file or directory in windows2019

### ISSUE THREAD

**Issue by minwoo-payhere** [1Password/install-cli-action#3]
I run jobs on window-2019
I think install-cli.sh path is not valid in windows
can you check this?

```yaml
jobs:
  build:
    runs-on: windows-2019
```

![image](https://github.com/1Password/install-cli-action/assets/128575786/c85a7c72-e625-4316-af91-273643d8e2aa)
